/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.CntasDAO;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author henry
 */
public class FrmCrearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form FrmCrearCuenta
     */
    private CntasDAO cntasDAO = new CntasDAO();

    public FrmCrearCuenta() {

        initComponents();
        this.setTitle("Creacion De Cuenta Bancaria");
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        Date fechaactual = java.sql.Date.valueOf(LocalDate.now());

        DateFormat df = new SimpleDateFormat("dd/mm/yyyy");
        String text = df.format(fechaactual);

        this.txtFchaCrcion.setText(text);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtsldo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdCnta = new javax.swing.JTextField();
        txtFchaCrcion = new javax.swing.JTextField();
        txtDescBnco = new javax.swing.JTextField();
        txtNmroIdntfccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMoneda = new javax.swing.JTextField();
        BtnVolverCrearPersona = new javax.swing.JButton();
        btnGuardarCrearCuenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(431, 435));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtsldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtsldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 120, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Saldo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Numero Cuenta");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Fecha Creacion");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Banco");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Cedula");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        txtIdCnta.setEditable(false);
        txtIdCnta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtIdCnta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 120, -1));

        txtFchaCrcion.setEditable(false);
        txtFchaCrcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFchaCrcion.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtFchaCrcionComponentAdded(evt);
            }
        });
        jPanel1.add(txtFchaCrcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 120, -1));

        txtDescBnco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtDescBnco, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 120, -1));

        txtNmroIdntfccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNmroIdntfccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNmroIdntfccionKeyTyped(evt);
            }
        });
        jPanel1.add(txtNmroIdntfccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 120, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Moneda");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        txtMoneda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 120, -1));

        BtnVolverCrearPersona.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnVolverCrearPersona.setText("Volver");
        BtnVolverCrearPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverCrearPersonaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVolverCrearPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        btnGuardarCrearCuenta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGuardarCrearCuenta.setText("Guardar");
        btnGuardarCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCrearCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Creacion De Cuenta Bancaria");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 280, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 431, 435));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverCrearPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverCrearPersonaActionPerformed
        // TODO add your handling code here:
        FrmInicio frmInicio = new FrmInicio();
        frmInicio.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BtnVolverCrearPersonaActionPerformed

    private void btnGuardarCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCrearCuentaActionPerformed

        if (txtDescBnco.getText().equals("") || txtMoneda.getText().equals("")
                || txtNmroIdntfccion.getText().equals("") || txtsldo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Todo Los campos Son obligatorios");
        } else {
        //de formato de fecha  
            //System.out.println(objSDF.format(objDate)); 
            String mensaje = null;
            String idBnco = txtDescBnco.getText();
            String NmroIdntfccion = txtNmroIdntfccion.getText();
            String mnda = txtMoneda.getText();
            double sldo = Double.parseDouble(txtsldo.getText());

       // Date date = new Date();
            // DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            // System.out.println("Fecha: "+dateFormat.format(date));
            mensaje = cntasDAO.insertarCuentas(java.sql.Date.valueOf(LocalDate.now()), idBnco, NmroIdntfccion, mnda, sldo);
            JOptionPane.showMessageDialog(null, mensaje);

        }

    }//GEN-LAST:event_btnGuardarCrearCuentaActionPerformed

    private void txtNmroIdntfccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNmroIdntfccionKeyTyped
        char validaCedula = evt.getKeyChar();

        if (validaCedula < '0' || validaCedula > '9') {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo debe ingresar Numeros");
        }
    }//GEN-LAST:event_txtNmroIdntfccionKeyTyped

    private void txtFchaCrcionComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtFchaCrcionComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFchaCrcionComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolverCrearPersona;
    private javax.swing.JButton btnGuardarCrearCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDescBnco;
    private javax.swing.JTextField txtFchaCrcion;
    private javax.swing.JTextField txtIdCnta;
    private javax.swing.JTextField txtMoneda;
    private javax.swing.JTextField txtNmroIdntfccion;
    private javax.swing.JTextField txtsldo;
    // End of variables declaration//GEN-END:variables
}
